# Generated by Django 3.0.2 on 2020-01-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='gallery')),
                ('note', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('price', models.IntegerField()),
                ('size', models.ManyToManyField(to='gallery.Size')),
            ],
        ),
    ]
