# Generated by Django 3.0.2 on 2020-01-31 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20200131_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='image',
            name='size',
        ),
        migrations.AddField(
            model_name='image',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.Size'),
        ),
    ]
