# Generated by Django 3.0.2 on 2020-02-07 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20200201_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.Position'),
        ),
    ]
