# Generated by Django 3.0.2 on 2020-02-18 15:09

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20200218_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to=gallery.models.content_file_name),
        ),
    ]
