# Generated by Django 3.0.2 on 2020-03-10 14:53

import django.core.validators
from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_auto_20200218_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to=gallery.models.content_file_name, validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])]),
        ),
    ]
