# Generated by Django 3.0.2 on 2020-02-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20200207_2357'),
        ('cart', '0005_auto_20200207_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderimages',
            field=models.ManyToManyField(to='gallery.Image'),
        ),
    ]
