# Generated by Django 3.0.2 on 2020-02-12 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_order_orderimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderimages',
        ),
    ]
