# Generated by Django 3.0 on 2020-01-14 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200114_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirt',
            name='size',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='products.Size'),
        ),
    ]
