# Generated by Django 3.0 on 2020-01-14 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_tshirt_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Size'),
        ),
    ]
