# Generated by Django 3.0 on 2020-01-14 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirt',
            name='supplier',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='products.Supplier'),
        ),
    ]
