# Generated by Django 3.0 on 2020-01-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_tshirt_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirt',
            name='nomenklatura',
            field=models.IntegerField(null=True),
        ),
    ]
