# Generated by Django 3.0 on 2020-01-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_tshirt_nomenklatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tshirt',
            name='color',
        ),
        migrations.AddField(
            model_name='tshirt',
            name='color',
            field=models.ManyToManyField(to='products.Color'),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
    ]
