# Generated by Django 3.0 on 2020-01-15 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200115_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tshirt',
            name='color',
        ),
        migrations.AddField(
            model_name='tshirt',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Color'),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=25),
        ),
        migrations.RemoveField(
            model_name='tshirt',
            name='size',
        ),
        migrations.AddField(
            model_name='tshirt',
            name='size',
            field=models.ManyToManyField(to='products.Size'),
        ),
    ]
