# Generated by Django 3.0 on 2020-01-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200115_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hexacode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
